# Generated by Django 4.2 on 2023-05-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_userdetails_chats"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="timestep",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
