# Generated by Django 4.0 on 2023-05-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_message_timestep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='chats',
        ),
    ]
